Handle some IllegalArgument cases in readBytes
java-native/jssc pull request #175
Opened 2024-11-22 03:00 UTC by hiddenalpha

The 2nd error covered here potentially could explain cases like https://github.com/java-native/jssc/issues/122 or related. Example: Passed-in 'byteCount' is either far too large or even a negative value which could trigger undesired behavior when used to allocate an array.

2024-11-22 23:38 UTC, hiddenalpha commented
Where can I find an anyhow useful error message about why so many builds are failing? I have no idea what I should fix.

2024-11-23 15:06 UTC, hiddenalpha commented
> I think GitHub actions' log area uses JavaScript to expand the relevant section and navigate to the error. Depending on your browser, if this isn't firing it might be hiding everything.

Thx. It really was that simple :) Didn't notice that actions require **yet another domain** to run JavaScript from.

2025-04-26 22:06 UTC, pietrygamat requested changes

2025-04-26 22:06 UTC, pietrygamat commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
I have run this on a branch with all the new PRs merged, and this does not work on macos pipeline:
https://github.com/pietrygamat/jssc/actions/runs/14685432138/job/41213415862

```
cmake-build:
     [exec] [ 50%] Building CXX object CMakeFiles/jssc.dir/src/main/cpp/_nix_based/jssc.cpp.o
     [exec] /Users/runner/work/jssc/jssc/src/main/cpp/_nix_based/jssc.cpp:29:10: fatal error: 'new' file not found
     [exec] #include <new> // std::bad_alloc
     [exec]          ^~~~~
     [exec] 1 error generated.
     [exec] make[2]: *** [CMakeFiles/jssc.dir/src/main/cpp/_nix_based/jssc.cpp.o] Error 1
     [exec] make[1]: *** [CMakeFiles/jssc.dir/all] Error 2
     [exec] make: *** [all] Error 2
```

2025-04-28 15:55 UTC, tresf commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
@pietrygamat I have a feeling this is due to GitHub switching their `macos-latest` runners from Intel to Apple Silicon exposing something obscurely broke with the SDK detection.  Since I have Apple Silicon to test on, I'll do some testing locally to see what's going on.

2025-04-28 16:42 UTC, tresf commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
Hmm... I was starting to scratch my head and then remembered we've improved some of the CI logic since this PR was created.  I'm going to fast-forward this PR just to be on the safe side.

2025-04-28 16:44 UTC, tresf commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
> Hmm... I was starting to scratch my head and then remembered we've improved some of the CI logic since this PR was created. I'm going to fast-forward this PR just to be on the safe side.

Oh, I forgot that @hiddenalpha doesn't allow pushes to his fork, so he'll have to do the fast-forward or we'll have to open a new PR to test this out.

2025-04-28 17:15 UTC, hiddenalpha commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
> forgot that @hiddenalpha doesn't allow pushes to his fork

Oh. Was not aware this little tick prevents further commits. Do you have access now?

2025-04-28 17:45 UTC, tresf commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
So I can reproduce this and ignoring the fast-forward, I still can't find a way to resolve this locally... Here's a thread that describes the problem, but sadly most of apple's forums use XCode which isn't necessarily helpful for cmake...  

https://developer.apple.com/forums/thread/106114
https://developer.apple.com/forums/thread/108537

For other C++ projects I've added `-stdlib=libc++` to the CMAKE_CXX_FLAGS, but IIRC that hasn't been needed for quite some time (and my tests with jssc didn't work).   I'm still investigating this...

2025-04-28 18:36 UTC, tresf commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
> > forgot that @hiddenalpha doesn't allow pushes to his fork
> 
> Oh. Was not aware this little tick prevents further commits. Do you have access now?

Thank you, I'll test it out soon!

2025-04-28 18:56 UTC, tresf commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
> Do you have access now?

Still shows access denied unfortunately.

2025-04-28 18:59 UTC, tresf commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
> > I'm still investigating this...
> 
> So it appears this `<new>` missing is caused by the `include/cpp/v1` folder missing from the 10.9 SDK folder, which the compiler expects. I'm going to write a small cmake patch that attempts to fix this...

Patch is done, just don't know where to put it... Here is it... https://gist.github.com/tresf/9e5043d431e5f9089a9b2f00c0a6fb64

2025-04-28 21:44 UTC, tresf commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
>  Is it still needed? Should I apply it onto the PR?

I think having standard C++ features will help us in the future, yes.

2025-04-28 21:53 UTC, tresf commented on src/main/cpp/_nix_based/jssc.cpp
> +#include <new> // std::bad_alloc
>  I just pushed a commit to see what gh-actions does with the malloc/free version.

Cool however we can't reliably test my patch's effectiveness now that this PR has been updated.

2025-05-09 22:27 UTC, pietrygamat commented on src/test/java/jssc/SerialNativeInterfaceTest.java
> +    }
I tried to make this test runnable on CI, and experimented with podman memory limits, but even then the exception is not thrown. Does this mean it's a skill issue, and I cannot set the limit correctly, or is the exception NOT thrown when expected and the test needs something to actually write to the buffer in order to fail successfully?

2025-05-10 08:51 UTC, hiddenalpha commented on src/main/cpp/_nix_based/jssc.cpp
> +    }
Hmmm. We could just use another exception? The question is which one.

Maybe we could use one of those? Other suggestions?

- [RuntimeException](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/RuntimeException.html) (arguing someting generic has gone bad)
- [MissingResourceException](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/util/MissingResourceException.html) (I just discovered this one. Was not aware that it exists)
- [NullPointerException](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/NullPointerException.html) (arguing we cannot use the `null` returned by malloc)
- [IllegalArgumentException](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/IllegalArgumentException.html) (arguing `byteCount` is too large)
- [UnsupportedOperationException](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/UnsupportedOperationException.html) (arguing working with more memory than we have is "not supported")

Note: I would prefer a standard (aka provided by JDK) rather than a custom one. As via JNI, our compiler wouldn't catch rename/move of our class, and we would end up with a [ClassNotFoundException](https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/ClassNotFoundException.html) as soon we hit this case during runtime. But even I don't like a custom exception here, it would be an option anyway.

2025-05-10 09:27 UTC, hiddenalpha commented on src/test/java/jssc/SerialNativeInterfaceTest.java
> +    }
Hmmm. I guess this could be tricky. Because there is a lot going on behind the scenes of malloc. I can just point out some guesses.

(Disclaimer: I don't know how excactly podman memory limits are implemented, or how they behave)

I myself did reproduce it using a qemu system VM (with a simple linux distro installed inside), limitted to 1GiB of total memory plus no swap.

- Maybe it has to do with memory overcommitting? So the system returns us an address speculatively, even the memory is not available right now? Nevertheless, it will just kill our program as soon we'll use the memory (no easy way to handle this case).
- Maybe we could do some [thrickery using `ulimit`](https://unix.stackexchange.com/a/746762/292722)? I use `ulimit` rarely. So not sure how to do it.

There are some more approaches. But due to required extra effort, I'm not sure if we should go one of those ways:

- Start a simple qemu system VM with limitted memory (lets say 1GiB), without any swap. Then run this specific test inside this VM. I guess lot of effort required for this to work with CI?
- Re-compile a 2nd version of jssc, where we mock `malloc` through a macro like
  `#define malloc(S) myMallocMock(S)`
  , and then having `myMallocMock()` implemented as
  `void* myMallocMock(size_t s){ return (s == SPECIAL_VALUE) ? NULL : malloc(s); }`
  This would require to have an separately compiled version of jssc just for this test. So extra effort too here. If you'd like to go this way, I could have a look to implement the C part with mocking the call. But I cannot help with integrating the extra re-build into CI.

2025-05-11 13:42 UTC, pietrygamat commented on src/main/cpp/_nix_based/jssc.cpp
> +    }
My vote goes for MissingResource, then Runtime

2025-05-11 13:45 UTC, pietrygamat commented on src/test/java/jssc/SerialNativeInterfaceTest.java
> +    }
Let's leave it as is for now in scope of this PR.

2025-05-12 15:44 UTC, hiddenalpha commented on src/main/cpp/_nix_based/jssc.cpp
> +    }
I tried to use `MissingResourceException` as discussed. But having a look at its extra ctor args, it seems not to be made for our use-case.  So I did fallback back to `RuntimeException` instead (let me know if its not ok).

2025-05-13 06:07 UTC, pietrygamat approved these changes

2025-05-14 19:05 UTC, tresf commented
No objections here... @pietrygamat did have any unresolved comments to sort before merging?

2025-05-14 21:00 UTC, merged